name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Move built jars
        run: |
          mkdir staging
          cp -r api/target/ staging
          cp -r bukkit/target/ staging
          cp -r bungee/target/ staging
          cp -r common/target/ staging
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging